name: SysDVR-Client

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - Client/**
      - ClientGUI/**
      - Libs/**
      - ReleaseClient.bat
      # but not the multiplatform builds
      - '!Client/Platform/Android/**'
      - '!Client/Platform/Linux/**'
  pull_request:
    branches: [ master ]
    paths:
      - Client/**
      - ClientGUI/**
      - Libs/**
      - ReleaseClient.bat
      - '!Client/Platform/Android/**'
      - '!Client/Platform/Linux/**'

jobs:
  build:
    # Must use windows-2019 as windows-latest doesn't have .net framework 4.5 needed to build the GUI
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    # SysDVR-Client uses .NET6
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x
    # SysDVR-ClientGUI uses net framework
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Run build script
      run: .\ReleaseClient.bat
    - uses: actions/upload-artifact@v3
      with:
        name: SysDVR-Client
        path: Client.7z
